name: "The Blues Issue"
url: www.thebluesissue.co.uk
baseurl: ""

navigation:
  - title: Home
    url: "/"
  - title: About
    url: "/about.html"
  - title: Gigs
    url: "/gigs.html"
  - title: Discography
    url: "/discography.html"
  - title: "Archive"
    url: "/archive.html"
  - title: Contact
    url: "/contact.html"

quotes:
  - quote: The Blues Issue knocked the ball right out of the park... Twice!”
    author: Swanage 2016
  - quote: A blinding set guys. Both guitars on fire. Would’ve been a great live recording
    author: 100 Club
